# Generated by Django 5.2.17 on 2026-09-14 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('tier', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('landlord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlord.landlord')),
            ],
        ),
    ]
