# Generated by Django 5.2.17 on 2026-09-14 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Review ID')),
                ('deposit_returned', models.BooleanField()),
                ('property_accuracy_rating', models.IntegerField()),
                ('responsiveness_rating', models.IntegerField()),
                ('overall_rating', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease.lease')),
            ],
        ),
    ]
