# Generated by Django 5.2.17 on 2026-09-14 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('listing_price', models.FloatField()),
                ('landlord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlord.landlord')),
            ],
        ),
    ]
